# Read Readme.md file!

version: '3.9'
services:
  redis:
    # https://hub.docker.com/_/redis
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  
  mongodb:
    # https://hub.docker.com/_/mongo
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db
  
  mysql:
    # https://hub.docker.com/_/mysql
    container_name: mysql_container
    image: mysql
    ## command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=jobber
      - MYSQL_DATABASE=jobber_auth
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
    ports:
      - '3306:3306'
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
  
  postgres:
    # https://hub.docker.com/_/postgres
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=jobber
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=jobber_reviews
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
  
  rabbitmq:
    # https://hub.docker.com/_/rabbitmq
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=jobber
      - RABBITMQ_DEFAULT_PASS=jobberpass
    ports:
      # AMQP protocol port
      - '5672:5672'
      # Management UI
      - '15672:15672'
    networks:
      - elastic

  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_start_a_single_node_cluster
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2 ### 8.10.4
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0 ###
      transport.host: 127.0.0.1 ###
      http.host: 0.0.0.0 ###
      xpack.security.enabled: "true" ### false
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      xpack.security.authc.token.enabled: "true" ###
      ELASTIC_PASSWORD: admin1234 ####
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
  
  kibana:
    # https://www.elastic.co/guide/en/kibana/current/docker.html
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.12.2 ### 8.10.4
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system ### elastic => kibana_system
      - ELASTICSEARCH_PASSWORD=kibana ### admin1234 => kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6N1dkRXZKR01TOHFVVWJ4amhQdFFWUQ
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"] ###
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
    depends_on: 
      - elasticsearch
  
  notifications:
    container_name: notification_container
    build:
      context: ../microservices/2-notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    env_file: ../microservices/2-notification-service/.env
    environment:
      - MS_NAME=NotificationMS
      - ENABLE_APM=0
      - NODE_ENV=development
      - SERVER_PORT=4001
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SENDER_EMAIL=
      - SENDER_EMAIL_PASSWORD=
      - SMTP_ENCRYPTION=null
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
      - APP_ICON_URL=https://i.ibb.co/Kyp2m0t/cover.png
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - elastic

  gateway:
    container_name: gateway_container
    build:
      context: ../microservices/1-gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    env_file: ../microservices/1-gateway-service/.env
    environment:
      - MS_NAME=GatewayMS
      - SERVER_PORT=4000
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - SECRET_KEY_ONE=zx032c5c3cfc37938ae6dd43d3a3ec7834
      - SECRET_KEY_TWO=zyd66e377018c0bc0b5772bbc9b131e6d9
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://localhost:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - redis
    networks:
      - elastic

networks:
  elastic:
    name: elastic

