# Read Readme.md file!

version: '3.9'
services:
  redis:
    # https://hub.docker.com/_/redis
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  
  mongodb:
    # https://hub.docker.com/_/mongo
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db
    networks:
      - elastic
  
  mysql:
    # https://hub.docker.com/_/mysql
    container_name: mysql_container
    image: mysql
    ## command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=jobber
      - MYSQL_DATABASE=jobber_auth
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
    ports:
      - '3306:3306'
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
    networks:
      - elastic
  
  postgres:
    # https://hub.docker.com/_/postgres
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=jobber
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=jobber_reviews
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
    networks:
      - elastic
  
  rabbitmq:
    # https://hub.docker.com/_/rabbitmq
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=jobber
      - RABBITMQ_DEFAULT_PASS=jobberpass
    ports:
      # AMQP protocol port
      - '5672:5672'
      # Management UI
      - '15672:15672'
    networks:
      - elastic

  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_start_a_single_node_cluster
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2 ### 8.10.4
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0 ###
      transport.host: 127.0.0.1 ###
      http.host: 0.0.0.0 ###
      xpack.security.enabled: "true" ### false
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      xpack.security.authc.token.enabled: "true" ###
      ELASTIC_PASSWORD: admin1234 ####
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
  
  kibana:
    # https://www.elastic.co/guide/en/kibana/current/docker.html
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.12.2 ### 8.10.4
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system ### elastic => kibana_system
      - ELASTICSEARCH_PASSWORD=kibana ### admin1234 => kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6ZkU5cV9RTUxTaHkxNjZGcXRpNndsdw
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"] ###
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
    depends_on: 
      - elasticsearch
    networks:
      - elastic

  # https://www.elastic.co/guide/en/observability/current/apm.html
  # https://www.elastic.co/guide/en/observability/current/apm-running-on-docker.html
  # https://www.elastic.co/guide/en/apm/agent/nodejs/current/intro.html
  apmServer:
    image: docker.elastic.co/apm/apm-server:8.12.2
    container_name: apm_server_container
    ports:
      - 8200:8200
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana_container:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana_container:5601
        -E apm-server.kibana.protocol=http
        -E strict.perms=false
        -E apm-server.auth.anonymous.enabled=true
  
  # https://www.elastic.co/guide/en/beats/metricbeat/8.12/metricbeat-overview.html
  metricbeat:
    # https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html
    container_name: metricbeat_container
    image: docker.elastic.co/beats/metricbeat:8.12.2
    restart: always
    user: root
    ports:
      - 5066:5066
    volumes:
      - ./metricbeat.yml/:/usr/share/metricbeat/metricbeat.yml:ro
      # docker module
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # system module
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    depends_on: 
      - elasticsearch
    networks:
      - elastic

  # https://www.elastic.co/guide/en/beats/heartbeat/current/running-on-docker.html
  heartbeat:
    container_name: heartbeat_container
    image: docker.elastic.co/beats/heartbeat:8.12.2
    user: root
    hostname: heartbeat
    cap_add:
      - NET_RAW
    command: ["--strict.perms=false"]
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    depends_on: 
      - elasticsearch
    networks:
      - elastic

  notifications:
    container_name: notification_container
    build:
      context: ../microservices/2-notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    env_file: ../microservices/2-notification-service/.env
    environment:
      - MS_NAME=NotificationMS
      - ENABLE_APM=0
      - NODE_ENV=development
      - SERVER_PORT=4001
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SENDER_EMAIL=
      - SENDER_EMAIL_PASSWORD=
      - SMTP_ENCRYPTION=null
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
      - APP_ICON_URL=https://i.ibb.co/Kyp2m0t/cover.png
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - elastic

  gateway:
    container_name: gateway_container
    build:
      context: ../microservices/1-gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    env_file: ../microservices/1-gateway-service/.env
    environment:
      - MS_NAME=GatewayMS
      - SERVER_PORT=4000
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - SECRET_KEY_ONE=zx032c5c3cfc37938ae6dd43d3a3ec7834
      - SECRET_KEY_TWO=zyd66e377018c0bc0b5772bbc9b131e6d9
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://auth_container:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - redis
    networks:
      - elastic

  auth:
    container_name: auth_container
    build:
      context: ../microservices/3-auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    env_file: ../microservices/3-auth-service/.env
    environment:
      - MS_NAME=AuthMS
      - SERVER_PORT=4002
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - CLOUD_NAME=
      - CLOUD_API_KEY=
      - CLOUD_API_SECRET=
      - USE_CLOUDINARY=false
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - MYSQL_DB=mysql://jobber:api@mysql_container:3306/jobber_auth
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mysql
    networks:
      - elastic

  users:
    container_name: users_container
    build:
      context: ../microservices/4-users-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4003:4003
    env_file: ../microservices/4-users-service/.env
    environment:
      - MS_NAME=UsersMS
      - SERVER_PORT=4003
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - CLOUD_NAME=
      - CLOUD_API_KEY=
      - CLOUD_API_SECRET=
      - USE_CLOUDINARY=false
      - API_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - MONGO_DATABASE_URL=mongodb://mongodb_container:27017/jobber-users
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=

    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic
  
  gig:
    container_name: gig_container
    build:
      context: ../microservices/5-gig-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4004:4004
    env_file: ../microservices/5-gig-service/.env
    environment:
      - MS_NAME=GigMS
      - SERVER_PORT=4004
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - CLOUD_NAME=
      - CLOUD_API_KEY=
      - CLOUD_API_SECRET=
      - USE_CLOUDINARY=false
      - API_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - MONGO_DATABASE_URL=mongodb://mongodb_container:27017/jobber-gig
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic

  chat:
    container_name: chat_container
    build:
      context: ../microservices/6-chat-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4005:4005
    env_file: ../microservices/6-chat-service/.env
    environment:
      - MS_NAME=ChatMS
      - SERVER_PORT=4005
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - CLOUD_NAME=
      - CLOUD_API_KEY=
      - CLOUD_API_SECRET=
      - USE_CLOUDINARY=false
      - API_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - MONGO_DATABASE_URL=mongodb://mongodb_container:27017/jobber-chat
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic
  
  order:
    container_name: order_container
    build:
      context: ../microservices/7-order-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4006:4006
    env_file: ../microservices/7-order-service/.env
    environment:
      - MS_NAME=OrderMS
      - SERVER_PORT=4006
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - CLOUD_NAME=
      - CLOUD_API_KEY=
      - CLOUD_API_SECRET=
      - USE_CLOUDINARY=false
      - STRIPE_API_KEY=sk_test_51OAXs6DTglvMeJPrlX1Lp9Mw7aXwlBbFJOLQdlkFv5mRKPkQdFrxvYN68xZ54wBr6VbP44khSM5UpPtfaixlMgcw00CIZEpmn5
      - CLIENT_URL=http://localhost:3000
      - API_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - MONGO_DATABASE_URL=mongodb://mongodb_container:27017/jobber-order
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=

    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic

  review:
    container_name: review_container
    build:
      context: ../microservices/8-review-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4007:4007
    env_file: ../microservices/8-review-service/.env
    environment:
      - MS_NAME=ReviewMS
      - SERVER_PORT=4007
      - NODE_ENV=development
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=ab7637698c4c8eb4ca24a82c69eb97f396
      - JWT_TOKEN=ac476502cec37af7510e1135a6d5135158
      - API_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
      - PG_DATABASE_HOST=localhost
      - PG_DATABASE_USER=jobber
      - PG_DATABASE_PASSWORD=api
      - PG_DATABASE_NAME=jobber_reviews
      - CLUSTER_TYPE=local
    depends_on:
      - elasticsearch
      - postgres
    networks:
      - elastic

networks:
  elastic:
    name: elastic

